const properties=[
 {id:1,name:'The Horizon Residence',location:'East Legon',type:'Villa',price:4850000,beds:4,baths:5,area:420,img:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',featured:1},
 {id:2,name:'Palm Court House',location:'Cantonments',type:'House',price:7200000,beds:5,baths:6,area:560,img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',featured:2},
 {id:3,name:'The Veranda',location:'Airport Residential Area',type:'Apartment',price:3650000,beds:3,baths:4,area:280,img:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80',featured:3},
 {id:4,name:'Olive Grove Villa',location:'Trasacco Valley',type:'Villa',price:9600000,beds:6,baths:7,area:760,img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80',featured:4},
 {id:5,name:'Serein House',location:'Labone',type:'House',price:5300000,beds:4,baths:4,area:390,img:'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',featured:5},
 {id:6,name:'Ridge Pavilion',location:'Ridge',type:'Apartment',price:4200000,beds:3,baths:3,area:310,img:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',featured:6},
 {id:7,name:'Aster Townhome',location:'East Legon',type:'Townhouse',price:2900000,beds:3,baths:3,area:250,img:'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80',featured:7},
 {id:8,name:'No. 18 Cantonments',location:'Cantonments',type:'Apartment',price:6800000,beds:4,baths:5,area:450,img:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80',featured:8}
];const money=n=>'GHS '+n.toLocaleString();
document.addEventListener('DOMContentLoaded',()=>{const h=document.querySelector('.site-header');addEventListener('scroll',()=>h?.classList.toggle('scrolled',scrollY>30),{passive:true});document.querySelector('.menu-toggle')?.addEventListener('click',e=>{document.querySelector('.nav-links').classList.toggle('open');document.body.classList.toggle('menu-open');e.currentTarget.textContent=document.body.classList.contains('menu-open')?'×':'☰'});const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.15});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));document.querySelectorAll('[data-parallax]').forEach(el=>addEventListener('scroll',()=>requestAnimationFrame(()=>{el.style.transform=`translateY(${scrollY*Number(el.dataset.parallax)}px)`}),{passive:true}));setTimeout(()=>document.querySelector('.loader')?.classList.add('done'),700);initCatalogue();initForms();initGallery();initCursor();initCounters()});
function initCatalogue(){const grid=document.querySelector('#property-grid');if(!grid)return;const render=list=>{grid.innerHTML=list.map(p=>`<a class="property-card reveal visible" href="property-details.html"><figure><img loading="lazy" src="${p.img}" alt="${p.name}"></figure><h3>${p.name}</h3><p>${p.location} · ${p.type}</p><div class="price">${money(p.price)}</div><div class="facts">${p.beds} BEDS · ${p.baths} BATHS · ${p.area} M²</div></a>`).join('');document.querySelector('#property-count').textContent=`${list.length} residences`};const apply=()=>{let x=[...properties],l=document.querySelector('#location')?.value,t=document.querySelector('#type')?.value,b=+document.querySelector('#beds')?.value||0,min=+document.querySelector('#min')?.value||0,max=+document.querySelector('#max')?.value||Infinity,s=document.querySelector('#sort')?.value;if(l)x=x.filter(p=>p.location===l);if(t)x=x.filter(p=>p.type===t);x=x.filter(p=>p.beds>=b&&p.price>=min&&p.price<=max);if(s==='low')x.sort((a,b)=>a.price-b.price);if(s==='high')x.sort((a,b)=>b.price-a.price);if(s==='newest')x.reverse();render(x)};render(properties);document.querySelectorAll('[data-filter]').forEach(x=>x.addEventListener('change',apply));document.querySelector('#search-form')?.addEventListener('submit',e=>{e.preventDefault();location.href='properties.html'})}
function initForms(){document.querySelectorAll('form[data-validate]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();let valid=[...form.querySelectorAll('[required]')].every(x=>x.value.trim());form.querySelector('.form-message').textContent=valid?'Thank you — our team will be in touch shortly.':'Please complete the required fields.';if(valid)form.reset()}))}
function initGallery(){const box=document.querySelector('.lightbox'),imgs=[...document.querySelectorAll('.gallery img')];if(!box)return;let i=0;const show=n=>{i=(n+imgs.length)%imgs.length;box.querySelector('img').src=imgs[i].src;box.classList.add('open')};imgs.forEach((x,n)=>x.parentElement.addEventListener('click',e=>{e.preventDefault();show(n)}));box.querySelector('.close').onclick=()=>box.classList.remove('open');box.querySelector('.next').onclick=()=>show(i+1);box.querySelector('.prev').onclick=()=>show(i-1)}
function initCursor(){const c=document.querySelector('.cursor');if(!c||!matchMedia('(pointer:fine)').matches)return;addEventListener('mousemove',e=>{c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'});document.querySelectorAll('.property-photo,.gallery a').forEach(x=>{x.addEventListener('mouseenter',()=>c.textContent=x.matches('.gallery a')?'EXPLORE':'VIEW');x.addEventListener('mouseleave',()=>c.textContent='')})}
function initCounters(){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;let n=+e.target.dataset.count,cur=0,t=setInterval(()=>{cur+=Math.ceil(n/35);e.target.textContent=Math.min(cur,n)+(e.target.dataset.suffix||'');if(cur>=n)clearInterval(t)},25);obs.unobserve(e.target)}));document.querySelectorAll('[data-count]').forEach(e=>obs.observe(e))}
